apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8s-supporting-folding-at-home.fullname" . }}
  labels:
    {{- include "k8s-supporting-folding-at-home.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-supporting-folding-at-home.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-supporting-folding-at-home.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "k8s-supporting-folding-at-home.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data-volume
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: USER
            value: "{{default "Anonymous" .Values.folding.user }}"
          - name: TEAM
            value: "{{default "0" .Values.folding.team }}"
          - name: PASSKEY
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-supporting-folding-at-home.fullname" . }}
                key: passkey
          - name: POWER
            value: "{{default "medium" .Values.folding.power }}"
          volumeMounts:
          - mountPath: /home/folding
            name: data-volume
          ports:
            - name: http
              containerPort: 7396
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 7396
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
