apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-supporting-folding-at-home.fullname" . }}
  labels:
    {{- include "k8s-supporting-folding-at-home.labels" . | nindent 4 }}
data:
  passkey: {{ default "" .Values.folding.passkey | b64enc | quote }}
