apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-supporting-folding-at-home
  namespace: default
  labels:
    app.kubernetes.io/name: k8s-supporting-folding-at-home
    app.kubernetes.io/version: "latest"
